ERROR - 2025-07-22 06:14:10 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 201)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:14:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known. 
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-22 06:14:21 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 201)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:14:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known. 
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-22 06:14:55 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\xampp\\htdocs...', 201)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('sql109.infinity...', 'if0_39525805', Object(SensitiveParameterValue), 'if0_39525805_ba...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known.  in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:14:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for sql109.infinityfree.com failed: No such host is known. 
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-22 06:16:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:16:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-22 06:16:57 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:16:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-07-22 06:17:41 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'db-webgis-dasar...', 3306, '', 0)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\belajar-gis-dasar-ci4\app\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
#5 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\Home->index()
#6 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\belajar-gis-dasar-ci4\public\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2025-07-22 06:17:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: home]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`
ORDER BY `created_at` DESC
 LIMIT 1', [], false)
 3 APPPATH\Models\ModelLokasi.php(35): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(20): App\Models\ModelLokasi->getLastInputDate()
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(58): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
DEBUG - 2025-07-22 07:59:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:09 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:34 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:00:37 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 08:01:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 12:47:23 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 12:47:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
DEBUG - 2025-07-22 12:47:27 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2025-07-22 13:33:02 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 13:33:02 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 13:33:06 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 13:33:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 13:33:37 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 13:33:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 13:35:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 13:35:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 13:35:43 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 13:35:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:11:14 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:11:14 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:11:24 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:11:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:12:19 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:12:19 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:12:35 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:12:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:34:11 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:34:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:34:22 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:34:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:34:32 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:34:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:36:04 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:36:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:46:34 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:46:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:49:04 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'100.64.0.3' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 38550, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'100.64.0.3' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:49:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'100.64.0.3' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:49:29 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'100.64.0.4' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 38550, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'100.64.0.4' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:49:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'100.64.0.4' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:49:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'100.64.0.12' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'railway', 38550, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'100.64.0.12' (using password: YES) in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:49:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'100.64.0.12' (using password: YES)
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:49:56 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:49:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:50:21 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:50:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:50:33 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:50:33 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 14:51:47 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 14:51:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 15:09:35 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('mysql-productio...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 15:09:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
ERROR - 2025-07-22 15:17:43 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('caboose.proxy.r...', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#7 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in E:\belajar-gis-dasar-ci4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\belajar-gis-dasar-ci4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\belajar-gis-dasar-ci4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\belajar-gis-dasar-ci4\app\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
#4 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(933): App\Controllers\User->index()
#5 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#6 E:\belajar-gis-dasar-ci4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 E:\belajar-gis-dasar-ci4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#8 E:\belajar-gis-dasar-ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#9 E:\belajar-gis-dasar-ci4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#10 E:\belajar-gis-dasar-ci4\system\rewrite.php(44): require_once('E:\\belajar-gis-...')
#11 {main}
CRITICAL - 2025-07-22 15:17:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[Method: GET, Route: /]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_lokasi`', [], false)
 3 APPPATH\Controllers\User.php(31): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\User->index()
 5 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\rewrite.php(44): require_once('E:\\belajar-gis-dasar-ci4\\public\\index.php')
